# Generated by Django 4.0.2 on 2022-07-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0007_alter_profile_fullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
